import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { STORAGE_KEYS } from "../../constants/storageKeys";

type Language = "en" | "es";

type LanguageContextValue = {
  lang: Language;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
  t: (text: string, values?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {},
  es: {
    "Job Safety Analysis": "Análisis de Seguridad de Trabajo",
    "Digital JSA": "JSA Digital",
    "Job Details": "Detalles del Trabajo",
    "New JSA": "Nuevo JSA",
    "Active JSA": "JSA activo",
    "Fill out the basic info for this load.": "Complete la información básica para esta carga.",
    "Fill out the basic info for this job.": "Complete la información básica para este trabajo.",
    "Driver Name": "Nombre del Conductor",
    "Truck #": "Camión #",
    "Job/Activity Name": "Trabajo/Actividad",
    Pusher: "Capataz",
    "Well Name": "Nombre del Pozo",
    "Add Well": "Agregar Pozo",
    "Added Wells": "Pozos Agregados",
    "Saved wells (tap to use):": "Pozos guardados (toca para usar):",
    "Saved locations (tap to use):": "Ubicaciones guardadas (toca para usar):",
    "Other Information": "Otra Información",
    Date: "Fecha",
    Location: "Ubicación",
    Locations: "Ubicaciones",
    Wells: "Pozos",
    "Save Favorite": "Guardar Favorito",
    "View Favorite Locations": "Ver Ubicaciones Favoritas",
    "Current JSA Locations": "Ubicaciones actuales del JSA",
    "Added Locations": "Ubicaciones agregadas",
    "Long press to remove": "Mantenga presionado para eliminar",
    "Next: Steps & Hazards": "Siguiente: Pasos y Peligros",
    "Resume active JSA": "Reanudar JSA activo",
    "Resume the JSA you started earlier today.": "Reanude el JSA que comenzó hoy.",
    "Start New JSA": "Iniciar nuevo JSA",
    "Start New": "Iniciar nuevo",
    "Fill in driver, truck #, and add at least one location to continue.":
      "Complete conductor, camión # y agregue al menos una ubicación para continuar.",
    "Steps & Hazards": "Pasos y Peligros",
    "PPE Checklist": "Lista de EPP",
    "Sign Off": "Cierre",
    "Add another location": "Agregar otra ubicación",
    "Only use if a new stop was added after starting this JSA.":
      "Use solo si se agregó una nueva parada después de iniciar este JSA.",
    "Locations reviewed:": "Ubicaciones revisadas:",
    "Review Next Location": "Revisar siguiente ubicación",
    "I am prepared for work": "Estoy preparado para el trabajo",
    "Signature (type your full name)": "Firma (escriba su nombre completo)",
    "Signature is required before submitting.": "Se requiere firma antes de enviar.",
    "All locations must be acknowledged before submitting.": "Todas las ubicaciones deben ser reconocidas antes de enviar.",
    "Additional Notes": "Notas Adicionales",
    "Submit JSA": "Enviar JSA",
    "Back to Job Details": "Volver a Detalles del Trabajo",
    "Safety Glasses": "Gafas de seguridad",
    "Safety Shoes": "Zapatos de seguridad",
    "FR Clothing": "Ropa FR",
    "Hearing Protection": "Protección auditiva",
    "Hard Hat": "Casco",
    "Respirator": "Respirador",
    "Chemical/Impact Gloves": "Guantes químicos/de impacto",
    "Four Gas Monitor": "Detector de cuatro gases",
    "Fall Protection": "Protección contra caídas",
    Other: "Otro",
    "Job Safety Analysis Report": "Informe de Análisis de Seguridad de Trabajo",
    "Generate PDF JSA report for this job.": "Generar reporte PDF de JSA para este trabajo.",
    Driver: "Conductor",
    "Truck #:": "Camión #:",
    Well: "Pozo",
    "Locations reviewed": "Ubicaciones revisadas",
    "Pusher:": "Capataz:",
    "Well:": "Pozo:",
    "Notes & Signature": "Notas y Firma",
    "JSA Completed": "JSA Completado",
    "Saved JSAs": "JSAs guardados",
    "Select a JSA to continue": "Seleccione un JSA para continuar",
    "No JSAs saved for today for this driver/truck.": "No hay JSAs guardados hoy para este conductor/camión.",
    "Add location": "Agregar ubicación",
    Settings: "Configuración",
    "Choose language": "Elija el idioma",
    Cancel: "Cancelar",
    "Saved": "Guardado",
    "Filter Saved JSAs": "Filtrar JSAs guardados",
    "Driver name": "Nombre del conductor",
    "Date (e.g., 2024-12-01)": "Fecha (ej., 2024-12-01)",
    "No saved JSAs yet.": "Aún no hay JSAs guardados.",
    "View favorite locations": "Ver ubicaciones favoritas",
    "Open saved JSAs": "Abrir JSAs guardados",
    "Today's JSAs": "JSAs de hoy",
    "No JSAs saved for today.": "No hay JSAs guardados hoy.",
    "PPE Required": "EPP Requerido",
    "Additional stop": "Parada adicional",
    "Prepared for Work": "Preparado para el trabajo",
    "Locations are managed on Job Details and Steps.": "Las ubicaciones se gestionan en Detalles del Trabajo y Pasos.",
    "No locations recorded.": "No se registraron ubicaciones.",
    "No PPE recorded.": "No se registró EPP.",
    "No checklist responses recorded.": "No se registraron respuestas de la lista.",
    "No additional notes provided.": "No se proporcionaron notas adicionales.",
    "Step": "Paso",
    "of": "de",
    "Hazard:": "Peligro:",
    "Controls:": "Controles:",
    "Previous": "Anterior",
    "Next": "Siguiente",
    "Other (specify)": "Otro (especificar)",
    "History": "Historial",
    "(acknowledged)": "(reconocido)",
    "(unreviewed)": "(sin revisar)",
    "Emergency Contacts": "Contactos de emergencia",
    "Full name": "Nombre completo",
    "Please review the JSA before starting this location": "Por favor revise el JSA antes de comenzar en esta ubicación",
    "Acknowledge & Continue": "Reconocer y continuar",
    "Add Location": "Agregar ubicación",
    "Enter location": "Ingresar ubicación",
    "Add": "Agregar",
    "Hazard": "Peligro",
    "Controls": "Controles",
    "Enter any notes": "Ingrese notas",
    "Add more stops as you go.": "Agregue más paradas a medida que avanza.",
    "Save location": "Guardar ubicación",
    "Company Contacts": "Contactos de la empresa",
    "Job/Activity": "Trabajo/Actividad",
    "View Favorite Wells": "Ver Pozos Favoritos",
    "Signature Required": "Firma requerida",
    "Locations Not Acknowledged": "Ubicaciones no reconocidas",
    "OK": "OK",
    "You have an incomplete JSA from today": "Tiene un JSA incompleto de hoy",
    "Pick Up Where I Left Off": "Continuar donde lo dejé",
    "Discard & Start New": "Descartar e iniciar nuevo",
    "Done": "Listo",
    "Defaults to today. Edit if needed.": "Predeterminado a hoy. Edite si es necesario.",
    "Fill in driver and truck # to continue.": "Complete conductor y camión # para continuar.",
    "Save & Add": "Guardar y agregar",
    "Remove": "Eliminar",
    "Remove Favorite": "Eliminar favorito",
    "Type & press Done to add": "Escriba y presione Listo para agregar",

    // JSA Step Titles
    "Driving on location": "Conduciendo en la ubicación",
    "Backing": "Retrocediendo",
    "Connecting hoses": "Conectando mangueras",
    "Loading fluids": "Cargando fluidos",
    "Checking levels on frac/production tanks": "Verificando niveles en tanques de fracturación/producción",
    "Offloading fluids": "Descargando fluidos",
    "Disconnecting hoses": "Desconectando mangueras",
    "Spill clean-up": "Limpieza de derrames",
    "Verify task is complete, job clean-up": "Verificar que la tarea esté completa, limpieza del trabajo",

    // JSA Hazards
    "Moving equipment, stationary equipment, personnel, flare, pressurized iron, wellheads, poor lighting/visibility, uneven ground, wet/soft ground, fire/explosion, triggering hazard.":
      "Equipo en movimiento, equipo estacionario, personal, antorcha, hierro presurizado, cabezales de pozo, poca iluminación/visibilidad, terreno irregular, terreno mojado/blando, fuego/explosión, peligro de activación.",
    "Poor lighting/visibility, damage to equipment, personal injury.":
      "Poca iluminación/visibilidad, daño al equipo, lesiones personales.",
    "Pressurized hoses, pinched fingers, poor connection, missing gaskets causing leaks, uneven/soft ground when moving hoses causing slips or falls, personal injury, static charge.":
      "Mangueras presurizadas, dedos pellizcados, mala conexión, juntas faltantes que causan fugas, terreno irregular/blando al mover mangueras causando resbalones o caídas, lesiones personales, carga estática.",
    "Overloading transport causes spills, personal exposure to fluids, and pinched fingers and hands while operating valves.":
      "Sobrecargar el transporte causa derrames, exposición personal a fluidos, y dedos y manos pellizcados al operar válvulas.",
    "Personal injury, slips, and trips when ascending and descending ladder, gases/fumes rising from the tank.":
      "Lesiones personales, resbalones y tropiezos al subir y bajar escaleras, gases/humos que salen del tanque.",
    "Overloading tanks can cause spills, personal exposure to fluids, overpressure of the vacuum tank, and pinched fingers while operating valves.":
      "Sobrecargar tanques puede causar derrames, exposición personal a fluidos, sobrepresión del tanque de vacío, y dedos pellizcados al operar válvulas.",
    "Pressurized hoses, spills, pinched fingers/hands, static charge.":
      "Mangueras presurizadas, derrames, dedos/manos pellizcados, carga estática.",
    "Working around overhead loads can cause injury, as can energized equipment, high-pressure iron causing damage to equipment and personal injury, and unknown fluids.":
      "Trabajar cerca de cargas elevadas puede causar lesiones, al igual que el equipo energizado, hierro de alta presión que causa daño al equipo y lesiones personales, y fluidos desconocidos.",
    "Slips, trips, falls while putting up equipment, leaving equipment or misplacing it while cleaning up, failing to ensure all job tasks are complete, causing poor work, and personal injury.":
      "Resbalones, tropiezos, caídas al guardar equipo, dejar equipo o extraviarlo durante la limpieza, no asegurar que todas las tareas estén completas, causando trabajo deficiente y lesiones personales.",

    // JSA Controls
    "Maintain 5 MPH on location at all times, scan the area while moving forward, maintain a safe distance from potential hazards, identify wind direction, muster points, and emergency evacuation routes, and maintain eye contact with moving personnel.":
      "Mantener 5 MPH en la ubicación en todo momento, escanear el área mientras avanza, mantener una distancia segura de peligros potenciales, identificar la dirección del viento, puntos de reunión y rutas de evacuación de emergencia, y mantener contacto visual con el personal en movimiento.",
    "Use forward movement if possible, use spotters when available, maintain constant radio contact with spotters at all times, walk the area before backing to identify potential hazards, and mark with orange cones.":
      "Usar movimiento hacia adelante si es posible, usar observadores cuando estén disponibles, mantener contacto de radio constante con los observadores en todo momento, caminar el área antes de retroceder para identificar peligros potenciales, y marcar con conos naranjas.",
    "Check for trapped pressure and point hoses in a safe direction before connecting hoses; wear appropriate gloves when connecting hoses; inspect hose, fittings, and gaskets before connection; scan the area while walking on surfaces; connect grounding to prevent static discharge.":
      "Verificar presión atrapada y apuntar mangueras en una dirección segura antes de conectar; usar guantes apropiados al conectar mangueras; inspeccionar manguera, accesorios y juntas antes de conectar; escanear el área mientras camina sobre superficies; conectar tierra para prevenir descarga estática.",
    "Maintain valve control and visual levels at all times, continuously scan hoses, valves, and manifolds for leaks, wear gloves and PPE prior to loading, and use headlights and transport lighting as needed.":
      "Mantener control de válvulas y niveles visuales en todo momento, escanear continuamente mangueras, válvulas y múltiples en busca de fugas, usar guantes y EPP antes de cargar, y usar faros y luces de transporte según sea necesario.",
    "Maintain three points of contact when ascending and descending ladders, wear four gas monitors at all times to identify gases/fumes, and use appropriate measurement tools to ensure accurate levels.":
      "Mantener tres puntos de contacto al subir y bajar escaleras, usar detectores de cuatro gases en todo momento para identificar gases/humos, y usar herramientas de medición apropiadas para asegurar niveles precisos.",
    "Maintain valve control and visual levels at all times, continuously scan hoses, valves, and manifolds for leaks, wear gloves and PPE before loading, use headlights and transport lighting as needed.":
      "Mantener control de válvulas y niveles visuales en todo momento, escanear continuamente mangueras, válvulas y múltiples en busca de fugas, usar guantes y EPP antes de cargar, usar faros y luces de transporte según sea necesario.",
    "Verify valves are closed and hoses are depressurized before disconnecting, watch hand placement, and place buckets under connections to mitigate spills.":
      "Verificar que las válvulas estén cerradas y las mangueras despresurizada antes de desconectar, cuidar la colocación de las manos, y colocar cubetas debajo de las conexiones para mitigar derrames.",
    "Understand overhead load fall radius, use caution while working around equipment, find and gauge high-pressure lines and mark and not run over them, question fluids being cleaned up, and maintain communication with employer in charge of equipment.":
      "Entender el radio de caída de cargas elevadas, usar precaución al trabajar cerca del equipo, encontrar y medir líneas de alta presión y marcarlas y no pasarlas por encima, cuestionar los fluidos que se limpian, y mantener comunicación con el empleador a cargo del equipo.",
    "Utilize appropriate lighting, scan area for hoses and uneven ground, watch footing, walk around equipment to ensure everything is stored for transport, and speak with the pusher or facilities operator to ensure all tasks are complete.":
      "Utilizar iluminación apropiada, escanear el área en busca de mangueras y terreno irregular, cuidar el paso, caminar alrededor del equipo para asegurar que todo esté guardado para el transporte, y hablar con el capataz u operador de instalaciones para asegurar que todas las tareas estén completas.",

    // Prepared for Work checklist items
    "I am properly trained for the job": "Estoy debidamente capacitado para el trabajo",
    "I have the tools & PPE needed for work": "Tengo las herramientas y EPP necesarios para el trabajo",
    "SDS": "HDS",

    // Additional translations
    "All Tasks": "Todas las tareas",
    "Loading": "Cargando",
    "Unloading": "Descargando",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "Share": "Compartir",
    "Task": "Tarea",
    "Edit JSA": "Editar JSA",
    "JSA Details": "Detalles del JSA",
    "Truck number": "Número de camión",
    "Job or activity": "Trabajo o actividad",
    "Pusher name": "Nombre del capataz",
    "Well name": "Nombre del pozo",
    "Other information": "Otra información",
    "Other Info": "Otra Información",
    "JSA has been updated.": "El JSA ha sido actualizado.",
    "Error": "Error",
    "Failed to save changes.": "Error al guardar los cambios.",
    "Save Changes": "Guardar Cambios",
    "PPE Selected": "EPP Seleccionado",
    "Notes": "Notas",
    "Signature": "Firma",
    "Ack": "Rec",
    "Enter notes": "Ingresar notas",
    "Enter driver name": "Ingrese nombre del conductor",
    "e.g. 105": "ej. 105",
    "Lease / site name": "Nombre del sitio / arrendamiento",
    "Notes or other info": "Notas u otra información",
    "Completed": "Completado",
    "Add Another Location": "Agregar otra ubicación",
    "Back": "Atrás",
    "PDF Preview": "Vista previa PDF",
    "Generating...": "Generando...",
    "Generate & Share PDF": "Generar y compartir PDF",
    "Back to Start": "Volver al inicio",
    "Home": "Inicio",
    "+ Add Well / Location": "+ Agregar pozo / ubicación",
    "Activity": "Actividad",
    "Add & Confirm Hazards": "Agregar y confirmar peligros",
    "Add a well or location to continue.": "Agregue un pozo o una ubicación para continuar.",
    "Add other PPE": "Agregar otro EPP",
    "Add Well / Location": "Agregar pozo / ubicación",
    "Added Location & Activity": "Ubicación y actividad agregadas",
    "Already submitted today": "Ya enviado hoy",
    "Are you sure you want to delete this JSA? This action cannot be undone.": "¿Está seguro de que desea eliminar este JSA? Esta acción no se puede deshacer.",
    "Are you sure you want to sign out?": "¿Está seguro de que desea cerrar sesión?",
    "Authentication is still active. Check your connection and retry sign out.": "La autenticación sigue activa. Revise su conexión e intente cerrar sesión de nuevo.",
    "By adding this location, I confirm that I have reviewed the hazards and controls for this job site.": "Al agregar esta ubicación, confirmo que revisé los peligros y controles de este sitio de trabajo.",
    "Cannot complete": "No se puede completar",
    "Close & Save": "Cerrar y guardar",
    "Close & Save JSA": "Cerrar y guardar JSA",
    "Close JSA": "Cerrar JSA",
    "Close menu": "Cerrar menú",
    "Close this JSA? The signed report will remain in Saved JSAs.": "¿Cerrar este JSA? El informe firmado permanecerá en JSA guardados.",
    "Company": "Empresa",
    "Completed JSAs will appear here": "Los JSA completados aparecerán aquí",
    "Completion not recorded": "Finalización no registrada",
    "Contacts": "Contactos",
    "Contacts are managed by your company in Dashboard Settings.": "Su empresa administra los contactos en la configuración del panel.",
    "Contacts updated successfully.": "Los contactos se actualizaron correctamente.",
    "Could not refresh JSAs. Showing records available on this phone. Try again when connected.": "No se pudieron actualizar los JSA. Se muestran los registros disponibles en este teléfono. Inténtelo de nuevo cuando tenga conexión.",
    "Delete JSA": "Eliminar JSA",
    "Done — Return to Work": "Listo — Volver al trabajo",
    "Draw Signature": "Dibujar firma",
    "Driver ID": "ID del conductor",
    "Driver Profile": "Perfil del conductor",
    "Driver Signature": "Firma del conductor",
    "e.g. 205": "ej. 205",
    "e.g. Production Water, Service Work...": "ej. Agua de producción, trabajo de servicio...",
    "Emergency": "Emergencia",
    "Enter a Job Type before adding a well or location.": "Ingrese un tipo de trabajo antes de agregar un pozo o una ubicación.",
    "Enter a Job Type to continue.": "Ingrese un tipo de trabajo para continuar.",
    "Enter other PPE": "Ingrese otro EPP",
    "Export / Share PDF": "Exportar / compartir PDF",
    "Exporting...": "Exportando...",
    "Failed to delete JSA. Please try again.": "No se pudo eliminar el JSA. Inténtelo de nuevo.",
    "Failed to load history. Pull down to try again.": "No se pudo cargar el historial. Deslice hacia abajo para intentarlo de nuevo.",
    "Failed to save contacts.": "No se pudieron guardar los contactos.",
    "Failed to save profile.": "No se pudo guardar el perfil.",
    "Hazard Review": "Revisión de peligros",
    "Job Type": "Tipo de trabajo",
    "Job Type Required": "Se requiere el tipo de trabajo",
    "JSA access could not be verified": "No se pudo verificar el acceso al JSA",
    "JSA Active": "JSA activo",
    "JSA Submitted": "JSA enviado",
    "JSA was not closed. Please retry.": "El JSA no se cerró. Inténtelo de nuevo.",
    "Language": "Idioma",
    "Launched from WellBuilt eWallet.": "Abierto desde WellBuilt eWallet.",
    "Launched from WellBuilt Suite.": "Abierto desde WellBuilt Suite.",
    "Launched from WellBuilt Tickets.": "Abierto desde WellBuilt Tickets.",
    "Legal Name": "Nombre legal",
    "Legal name is required": "Se requiere el nombre legal",
    "Loading wells and SWDs...": "Cargando pozos y SWD...",
    "More": "Más",
    "Name": "Nombre",
    "Name is set from your login profile.": "El nombre se obtiene de su perfil de inicio de sesión.",
    "No saved JSAs": "No hay JSA guardados",
    "No signature saved.": "No hay una firma guardada.",
    "Not saved": "No guardado",
    "Other PPE": "Otro EPP",
    "Phone": "Teléfono",
    "Please review all steps before continuing.": "Revise todos los pasos antes de continuar.",
    "Please sign before submitting. Tap the signature area to draw your signature.": "Firme antes de enviar. Toque el área de firma para dibujar su firma.",
    "Previous period": "Período anterior",
    "Print full name": "Escriba el nombre completo",
    "Profile updated successfully.": "El perfil se actualizó correctamente.",
    "Re-sign": "Volver a firmar",
    "Read & Acknowledge JSA": "Leer y reconocer el JSA",
    "Read Safety Steps": "Leer los pasos de seguridad",
    "record": "registro",
    "records": "registros",
    "Refresh incomplete": "Actualización incompleta",
    "Retry": "Reintentar",
    "Return to WB eW": "Volver a WB eW",
    "Return to WB S": "Volver a WB S",
    "Return to WB T": "Volver a WB T",
    "Review & Submit": "Revisar y enviar",
    "Review All Steps": "Revisar todos los pasos",
    "Save Contacts": "Guardar contactos",
    "Save Profile": "Guardar perfil",
    "Saved location": "Ubicación guardada",
    "Saved on this device — cloud sync hasn't finished yet. It will remain in Saved JSAs.": "Guardado en este dispositivo; la sincronización con la nube aún no termina. Permanecerá en JSA guardados.",
    "Search NDIC wells or enter manually...": "Buscar pozos NDIC o ingresar manualmente...",
    "Search wells / SWDs or enter location...": "Buscar pozos / SWD o ingresar una ubicación...",
    "Shift": "Turno",
    "Sign Out": "Cerrar sesión",
    "Sign Out Incomplete": "Cierre de sesión incompleto",
    "Signature was not saved. Please retry.": "La firma no se guardó. Inténtelo de nuevo.",
    "Signed": "Firmado",
    "Standalone JSAs do not require a shift. Company access could not be confirmed. Return to Suite and reopen JSA to retry.": "Los JSA independientes no requieren un turno. No se pudo confirmar el acceso de la empresa. Vuelva a Suite y abra JSA de nuevo para reintentar.",
    "Stay on JSA": "Permanecer en JSA",
    "Submission Not Complete": "Envío incompleto",
    "Submitted": "Enviado",
    "Tap to Sign": "Toque para firmar",
    "This will finalize this JSA with all job sites visited. A final PDF will be saved.": "Esto finalizará el JSA con todos los sitios visitados. Se guardará un PDF final.",
    "Trailer #": "Remolque #",
    "Truck": "Camión",
    "Try Again": "Intentar de nuevo",
    "Update Signature": "Actualizar firma",
    "Well / Location": "Pozo / ubicación",
    "Well or location name": "Nombre del pozo o ubicación",
    "Well or Location Name": "Nombre del pozo o ubicación",
    "Your JSA could not be saved to the cloud yet, so WB Tickets cannot verify it. Check connectivity and tap Retry — your entries and signature are kept.": "Su JSA aún no se pudo guardar en la nube, por lo que WB Tickets no puede verificarlo. Revise la conexión y toque Reintentar; sus datos y firma se conservarán.",
    "Your JSA has been submitted and saved.": "Su JSA se envió y guardó.",
    "Your shift is active. WellBuilt will record each pickup and drop-off automatically as you work. Read the safety steps below to acknowledge today's JSA.": "Su turno está activo. WellBuilt registrará automáticamente cada carga y descarga mientras trabaja. Lea los pasos de seguridad para reconocer el JSA de hoy.",
    "6-12 characters": "6-12 caracteres",
    "a different printer": "una impresora diferente",
    "Access Denied": "Acceso denegado",
    "Acknowledge JSA": "Reconocer JSA",
    "Acknowledge this JSA": "Reconocer este JSA",
    "Acknowledged": "Reconocido",
    "Acknowledged by": "Reconocido por",
    "Acknowledged: {date}": "Reconocido: {date}",
    "Add location / activity": "Agregar ubicación / actividad",
    "Added": "Agregado",
    "Added location / activity": "Ubicación / actividad agregada",
    "Added locations without an * were acknowledged under the same company assessment. Location-specific differences are listed separately.": "Las ubicaciones agregadas sin * se reconocieron bajo la misma evaluación de la empresa. Las diferencias específicas de cada ubicación se muestran por separado.",
    "Added:": "Agregado:",
    "Addition not confirmed": "Adición no confirmada",
    "Additional controls:": "Controles adicionales:",
    "Additional hazards:": "Peligros adicionales:",
    "Additional task assessment": "Evaluación adicional de la tarea",
    "Already added": "Ya se agregó",
    "An administrator will review your request shortly.": "Un administrador revisará su solicitud pronto.",
    "Authentication could not be cleared and verified. Retry before opening standalone or changing drivers.": "No se pudo borrar y verificar la autenticación. Inténtelo de nuevo antes de abrir el modo independiente o cambiar de conductor.",
    "Bluetooth device": "Dispositivo Bluetooth",
    "By adding this location, I acknowledge that I have reviewed this work and the applicable hazards, controls, and PPE in this JSA.": "Al agregar esta ubicación, reconozco que revisé este trabajo y los peligros, controles y EPP aplicables en este JSA.",
    "Cancel registration": "Cancelar registro",
    "Cannot continue": "No se puede continuar",
    "CDL": "Licencia comercial",
    "Check existing JSA": "Revisar JSA existente",
    "Checking for approval...": "Buscando aprobación...",
    "Checking open JSAs…": "Buscando JSA abiertos…",
    "Choose Regular printer when printing a JSA. Android’s print dialog handles HP Print Service and other installed printer services.": "Elija Impresora normal al imprimir un JSA. El diálogo de impresión de Android administra HP Print Service y otros servicios instalados.",
    "Clear": "Borrar",
    "Close": "Cerrar",
    "Close JSA?": "¿Cerrar JSA?",
    "Close standalone JSAs": "Cerrar JSA independientes",
    "Close Switcher": "Cerrar Selector",
    "Close these {count} standalone JSAs? Shift JSAs are handled through Suite.": "¿Cerrar estos {count} JSA independientes? Los JSA del turno se administran mediante Suite.",
    "Close this JSA": "Cerrar este JSA",
    "Company assessments": "Evaluaciones de la empresa",
    "Company logo": "Logotipo de la empresa",
    "Confirm Discard": "Confirmar descarte",
    "Continue": "Continuar",
    "Continue to App": "Continuar a la aplicación",
    "Could not load the complete report. Retry when connected.": "No se pudo cargar el informe completo. Inténtelo de nuevo cuando tenga conexión.",
    "Customer not recorded": "Cliente no registrado",
    "Default assessment": "Evaluación predeterminada",
    "Describe reason...": "Describa el motivo...",
    "Different company task assessment": "Evaluación de tarea diferente de la empresa",
    "Different hazards, controls, or PPE at this location": "Peligros, controles o EPP diferentes en esta ubicación",
    "Discard": "Descartar",
    "Discard JSA for {date}?": "¿Descartar el JSA del {date}?",
    "Driver signature": "Firma del conductor",
    "End standalone day?": "¿Terminar el día independiente?",
    "English": "Inglés",
    "Enter the company name your employer gave you": "Ingrese el nombre de la empresa que le dio su empleador",
    "Español": "Español",
    "Field Operations": "Operaciones de campo",
    "Find / change thermal printer": "Buscar / cambiar impresora térmica",
    "Full legal name (for documents)": "Nombre legal completo (para documentos)",
    "Generated by WellBuilt JSA": "Generado por WellBuilt JSA",
    "Generated: {date}": "Generado: {date}",
    "Go to home screen": "Ir a la pantalla de inicio",
    "Good afternoon": "Buenas tardes",
    "Good evening": "Buenas noches",
    "Good morning": "Buenos días",
    "Hazards": "Peligros",
    "Hazards:": "Peligros:",
    "I have read this step and its controls.": "He leído este paso y sus controles.",
    "If you believe this is a mistake, contact an administrator.": "Si cree que esto es un error, comuníquese con un administrador.",
    "Independent registration is temporarily unavailable while governed identity support is completed.": "El registro independiente no está disponible temporalmente mientras se completa la compatibilidad con la identidad administrada.",
    "Job": "Trabajo",
    "JSA details": "Detalles del JSA",
    "JSA Reviewed": "JSA revisado",
    "JSA status could not be verified": "No se pudo verificar el estado del JSA",
    "Legal name": "Nombre legal",
    "Loading Switcher…": "Cargando Selector…",
    "Location-specific differences": "Diferencias específicas de la ubicación",
    "Locations covered": "Ubicaciones cubiertas",
    "Modal": "Ventana modal",
    "New JSA / another oil company": "Nuevo JSA / otra compañía petrolera",
    "No oil companies are set on your WB driver profile. Set up your customer list to enable well suggestions. You can still enter a location manually.": "No hay compañías petroleras configuradas en su perfil de conductor de WB. Configure su lista de clientes para habilitar sugerencias de pozos. Aún puede ingresar una ubicación manualmente.",
    "No open JSAs.": "No hay JSA abiertos.",
    "No thermal printer selected": "No se seleccionó una impresora térmica",
    "none": "ninguna",
    "Not recorded": "No registrado",
    "Oil company": "Compañía petrolera",
    "Oil Company": "Compañía petrolera",
    "Open": "Abrir",
    "Open {app}": "Abrir {app}",
    "Open Bluetooth settings": "Abrir configuración de Bluetooth",
    "Open Bluetooth settings on your phone to pair the printer.": "Abra la configuración de Bluetooth del teléfono para emparejar la impresora.",
    "Open JSA settings": "Abrir configuración de JSA",
    "Open JSAs": "JSA abiertos",
    "Resume": "Reanudar",
    "Open Printer settings to choose a printer.": "Abra la configuración de impresoras para elegir una impresora.",
    "Open standalone login": "Abrir inicio de sesión independiente",
    "Original": "Original",
    "Original signature": "Firma original",
    "Original signature and later acknowledgements remain separate.": "La firma original y los reconocimientos posteriores permanecen separados.",
    "Please select a reason or describe in at least 3 characters.": "Seleccione un motivo o descríbalo con al menos 3 caracteres.",
    "Please sign to acknowledge this JSA.": "Firme para reconocer este JSA.",
    "PPE": "EPP",
    "PPE already selected": "EPP ya seleccionado",
    "PPE changes:": "Cambios de EPP:",
    "PPE selected": "EPP seleccionado",
    "PPE:": "EPP:",
    "Preparation:": "Preparación:",
    "Prepared for work": "Preparado para el trabajo",
    "Preparing thermal report…": "Preparando informe térmico…",
    "Print dialog closed. Check your printer.": "Se cerró el diálogo de impresión. Revise su impresora.",
    "Print JSA": "Imprimir JSA",
    "Print JSA with additions": "Imprimir JSA con adiciones",
    "Print unavailable": "Impresión no disponible",
    "Printer selection changed to {printer}. Nothing was sent. Check the selection, then tap Thermal printer again.": "La selección cambió a {printer}. No se envió nada. Revise la selección y toque Impresora térmica de nuevo.",
    "Printer settings": "Configuración de impresoras",
    "Printers": "Impresoras",
    "Printing {page} of {total}…": "Imprimiendo {page} de {total}…",
    "Printing did not complete": "La impresión no se completó",
    "Read selected assessments": "Leer evaluaciones seleccionadas",
    "Read this JSA": "Leer este JSA",
    "Reason required": "Se requiere un motivo",
    "Record": "Registro",
    "Recorded after the original signature; original assessment unchanged.": "Registrado después de la firma original; la evaluación original no cambió.",
    "Redirecting...": "Redirigiendo...",
    "Reference only: the original step text was not stored with this older JSA. The steps below are the current built-in reference, not proof of what was originally read.": "Solo como referencia: el texto original de los pasos no se guardó con este JSA anterior. Los pasos siguientes son la referencia integrada actual, no una prueba de lo que se leyó originalmente.",
    "Registration Approved!": "¡Registro aprobado!",
    "Registration Pending": "Registro pendiente",
    "Regular printer": "Impresora normal",
    "Remind me later": "Recordarme más tarde",
    "Required: audit reason. This is logged and visible to your company's safety manager.": "Obligatorio: motivo de auditoría. Esto se registra y queda visible para el gerente de seguridad de su empresa.",
    "Retry loading assessment": "Reintentar cargar la evaluación",
    "Retry loading assessments": "Reintentar cargar las evaluaciones",
    "Retry loading JSA": "Reintentar cargar el JSA",
    "Retry loading JSAs": "Reintentar cargar los JSA",
    "Retry secure check": "Reintentar verificación segura",
    "Retry sign out": "Reintentar cerrar sesión",
    "Return to WellBuilt": "Volver a WellBuilt",
    "Roll width": "Ancho del rollo",
    "Search wells / SWDs or enter location": "Buscar pozos / SWD o ingresar ubicación",
    "Search your oil companies": "Buscar sus compañías petroleras",
    "See the original JSA.": "Consulte el JSA original.",
    "Select an oil company for well suggestions. SWDs and manual locations remain available.": "Seleccione una compañía petrolera para ver sugerencias de pozos. Los SWD y las ubicaciones manuales siguen disponibles.",
    "Select the assessments you need to read for this JSA. One assessment can cover several tasks when the wording is the same.": "Seleccione las evaluaciones que debe leer para este JSA. Una evaluación puede cubrir varias tareas cuando el texto es el mismo.",
    "Selected printer: {printer}": "Impresora seleccionada: {printer}",
    "Sent to printer. Check the full printed copy.": "Enviado a la impresora. Revise la copia impresa completa.",
    "Shift not verified": "Turno no verificado",
    "Shift Timer": "Temporizador de turno",
    "Sign In Failed": "Error al iniciar sesión",
    "Sign out": "Cerrar sesión",
    "Sign out and clear local JSA session": "Cerrar sesión y borrar la sesión local de JSA",
    "Sign out incomplete": "Cierre de sesión incompleto",
    "Signature image unavailable in this saved record.": "La imagen de la firma no está disponible en este registro guardado.",
    "Signature required": "Se requiere firma",
    "Signed:": "Firmado:",
    "Signing in from WellBuilt Suite...": "Iniciando sesión desde WellBuilt Suite...",
    "Some locations could not load. Tap to retry.": "No se pudieron cargar algunas ubicaciones. Toque para reintentar.",
    "Some shift statuses could not be verified. Retry before starting another assessment.": "No se pudieron verificar algunos estados del turno. Inténtelo de nuevo antes de iniciar otra evaluación.",
    "Start Over": "Comenzar de nuevo",
    "Steps, hazards and controls": "Pasos, peligros y controles",
    "Switcher": "Selector",
    "Task-specific required-job assessments are not enabled yet. Return to Suite.": "Las evaluaciones obligatorias específicas de la tarea aún no están habilitadas. Vuelva a Suite.",
    "The signed report and its additions stay available.": "El informe firmado y sus adiciones seguirán disponibles.",
    "Thermal and regular paper printers": "Impresoras térmicas y de papel normal",
    "Thermal printer": "Impresora térmica",
    "Thermal printer brand": "Marca de impresora térmica",
    "These JSAs have wells you visited but never signed off. Finish them or discard with a reason for the audit trail.": "Estos JSA tienen pozos que visitó pero nunca cerró. Termínelos o descártelos con un motivo para el registro de auditoría.",
    "This is a modal": "Esta es una ventana modal",
    "This JSA is closed. Start a new JSA for additional work.": "Este JSA está cerrado. Inicie uno nuevo para trabajo adicional.",
    "Today": "Hoy",
    "Use the company assessment and PPE already recorded on this JSA.": "Use la evaluación de la empresa y el EPP ya registrados en este JSA.",
    "Used on printed JSA forms and signatures": "Se usa en formularios JSA impresos y firmas",
    "Uses WB-T’s Brother RJ-4230B connection.": "Usa la conexión Brother RJ-4230B de WB-T.",
    "Uses WB-T’s ESC/POS Bluetooth connection. Your printer must support ESC/POS mode; the brand alone does not guarantee compatibility.": "Usa la conexión Bluetooth ESC/POS de WB-T. Su impresora debe admitir el modo ESC/POS; la marca por sí sola no garantiza compatibilidad.",
    "Verified personal protective equipment for this job.": "Equipo de protección personal verificado para este trabajo.",
    "Version": "Versión",
    "Welcome to WellBuilt JSA": "Bienvenido a WellBuilt JSA",
    "Welcome, {name}! Your registration has been approved.": "¡Bienvenido, {name}! Su registro ha sido aprobado.",
    "Well / location": "Pozo / ubicación",
    "Which tasks will you perform?": "¿Qué tareas realizará?",
    "Yesterday": "Ayer",
    "Your company name": "Nombre de su empresa",
    "Your registration as \"{name}\" is waiting for approval.": "Su registro como \"{name}\" está esperando aprobación.",
    "Your registration request was denied.": "Su solicitud de registro fue denegada.",
    "Your registration will need to be approved by an administrator.": "Su registro deberá ser aprobado por un administrador.",
    "A newer sign-in attempt replaced this one.": "Un intento de inicio de sesión más reciente reemplazó este.",
    "Acknowledge": "Reconocer",
    "Acknowledge and add location": "Reconocer y agregar ubicación",
    "Add signature": "Agregar firma",
    "Add your job and locations, then read your JSA.": "Agregue su trabajo y ubicaciones, luego lea su JSA.",
    "Adding…": "Agregando…",
    "Additional hazards": "Peligros adicionales",
    "All published assessments are already covered by this JSA.": "Todas las evaluaciones publicadas ya están cubiertas por este JSA.",
    "Already completed": "Ya completado",
    "Already registered?": "¿Ya está registrado?",
    "An active WellBuilt shift is required. Return to WellBuilt Tickets and launch again.": "Se requiere un turno activo de WellBuilt. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "Checking thermal printer…": "Revisando la impresora térmica…",
    "Closed": "Cerrado",
    "Closed JSA": "JSA cerrado",
    "Closing…": "Cerrando…",
    "Connection error. Please try again.": "Error de conexión. Inténtelo de nuevo.",
    "Controls for these differences": "Controles para estas diferencias",
    "Could not load your JSAs. Check your sign-in and retry.": "No se pudieron cargar sus JSA. Revise su inicio de sesión e inténtelo de nuevo.",
    "Could not refresh JSAs. Showing records available on this phone. Retry when connected.": "No se pudieron actualizar los JSA. Se muestran los registros disponibles en este teléfono. Inténtelo de nuevo cuando tenga conexión.",
    "Could not reach WellBuilt services. Return to WellBuilt Tickets and try again.": "No se pudo conectar con los servicios de WellBuilt. Vuelva a WellBuilt Tickets e inténtelo de nuevo.",
    "Could not save printer settings. Try again.": "No se pudo guardar la configuración de la impresora. Inténtelo de nuevo.",
    "Could not sign in": "No se pudo iniciar sesión",
    "Could not sign in to WellBuilt JSA. Return to WellBuilt Tickets and launch again.": "No se pudo iniciar sesión en WellBuilt JSA. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "Could not submit registration": "No se pudo enviar el registro",
    "Create a passcode": "Cree un código de acceso",
    "Create Passcode": "Crear código de acceso",
    "Current WellBuilt shift could not be verified. Return to WellBuilt and try again.": "No se pudo verificar el turno actual de WellBuilt. Vuelva a WellBuilt e inténtelo de nuevo.",
    "Current WellBuilt shift could not be verified. Return to WellBuilt Tickets and launch again.": "No se pudo verificar el turno actual de WellBuilt. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "Display name (e.g., MBurger)": "Nombre para mostrar (ej., MBurger)",
    "Display Name": "Nombre para mostrar",
    "Duplicate of another JSA": "Duplicado de otro JSA",
    "End standalone day": "Terminar el día independiente",
    "Enter your info to register with your company": "Ingrese su información para registrarse con su empresa",
    "Enter your name and passcode to sign in": "Ingrese su nombre y código de acceso para iniciar sesión",
    "Forgot to finish": "Olvidé terminar",
    "I have the tools and PPE needed for work": "Tengo las herramientas y el EPP necesarios para el trabajo",
    "Invalid name or passcode.": "Nombre o código de acceso no válido.",
    "JSA is not available for this shift. Return to WellBuilt Tickets and launch again.": "El JSA no está disponible para este turno. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "JSA no longer applicable": "El JSA ya no aplica",
    "New Employee Registration": "Registro de empleado nuevo",
    "New employee?": "¿Empleado nuevo?",
    "No paired devices found. Pair your printer in Android Bluetooth settings.": "No se encontraron dispositivos emparejados. Empareje su impresora en la configuración de Bluetooth de Android.",
    "No published task assessments are available.": "No hay evaluaciones de tareas publicadas disponibles.",
    "Old sign-in data could not be cleared. Retry secure sign-in cleanup.": "No se pudieron borrar los datos anteriores de inicio de sesión. Intente de nuevo la limpieza del inicio de sesión seguro.",
    "Ongoing JSA": "JSA en curso",
    "Opening regular printer…": "Abriendo impresora normal…",
    "Opening WellBuilt JSA…": "Abriendo WellBuilt JSA…",
    "Paired devices refreshed. Tap the printer you want to use.": "Se actualizaron los dispositivos emparejados. Toque la impresora que desea usar.",
    "Passcode": "Código de acceso",
    "Passcode contains invalid characters": "El código de acceso contiene caracteres no válidos",
    "Passcode must be 12 characters or less": "El código de acceso debe tener 12 caracteres o menos",
    "Passcode must be at least 6 characters": "El código de acceso debe tener al menos 6 caracteres",
    "Please create a passcode": "Cree un código de acceso",
    "PPE changes (optional)": "Cambios de EPP (opcional)",
    "Read": "Leído",
    "Read and acknowledged": "Leído y reconocido",
    "Registration approved. Please sign in.": "Registro aprobado. Inicie sesión.",
    "Register here": "Regístrese aquí",
    "Reopen this JSA when connected to review its latest additions.": "Vuelva a abrir este JSA cuando tenga conexión para revisar sus adiciones más recientes.",
    "Retry when connected.": "Inténtelo de nuevo cuando tenga conexión.",
    "Return to WellBuilt and open JSA again.": "Vuelva a WellBuilt y abra JSA de nuevo.",
    "Return to WellBuilt Tickets": "Volver a WellBuilt Tickets",
    "Saved JSA": "JSA guardado",
    "Secure sign-in could not be verified. Check your connection and retry.": "No se pudo verificar el inicio de sesión seguro. Revise su conexión e inténtelo de nuevo.",
    "Secure sign-in could not be verified. Retry opening JSA.": "No se pudo verificar el inicio de sesión seguro. Intente abrir JSA de nuevo.",
    "Secure sign-in could not verify this JSA session.": "El inicio de sesión seguro no pudo verificar esta sesión de JSA.",
    "Secure sign-in requires cleanup before retrying.": "El inicio de sesión seguro requiere una limpieza antes de volver a intentarlo.",
    "Secure WellBuilt sign-in could not be verified. Return to WellBuilt and try again.": "No se pudo verificar el inicio de sesión seguro de WellBuilt. Vuelva a WellBuilt e inténtelo de nuevo.",
    "Shift JSA": "JSA del turno",
    "Sign In": "Iniciar sesión",
    "Sign in": "Iniciar sesión",
    "Sign-in changed during verification. Return to WellBuilt and retry.": "El inicio de sesión cambió durante la verificación. Vuelva a WellBuilt e inténtelo de nuevo.",
    "Sign out could not be verified.": "No se pudo verificar el cierre de sesión.",
    "Signature captured": "Firma capturada",
    "Signing in to WellBuilt JSA…": "Iniciando sesión en WellBuilt JSA…",
    "Signing out...": "Cerrando sesión...",
    "Some JSAs could not close. The remaining open records are shown below.": "No se pudieron cerrar algunos JSA. Los registros que siguen abiertos se muestran abajo.",
    "Some shift statuses could not be verified. Saved JSAs remain available.": "No se pudieron verificar algunos estados del turno. Los JSA guardados siguen disponibles.",
    "Standalone": "Independiente",
    "Submitting your registration...": "Enviando su registro...",
    "Submit Registration": "Enviar registro",
    "SWDs could not load. You can enter a location manually.": "No se pudieron cargar los SWD. Puede ingresar una ubicación manualmente.",
    "The previous printer is no longer paired. Tap the printer you want to use below.": "La impresora anterior ya no está emparejada. Toque abajo la impresora que desea usar.",
    "This account has been deactivated.": "Esta cuenta ha sido desactivada.",
    "This action is unavailable in this version. Update WellBuilt JSA to continue.": "Esta acción no está disponible en esta versión. Actualice WellBuilt JSA para continuar.",
    "This JSA action is not available now. Return to WellBuilt Tickets and launch again.": "Esta acción de JSA no está disponible ahora. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request does not match the current shift. Return to WellBuilt Tickets and launch again.": "Esta solicitud de JSA no corresponde al turno actual. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request has expired. Return to WellBuilt Tickets and launch again.": "Esta solicitud de JSA venció. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request is already completed. Return to WellBuilt Tickets.": "Esta solicitud de JSA ya está completa. Vuelva a WellBuilt Tickets.",
    "This JSA request is no longer available. Return to WellBuilt Tickets and launch again.": "Esta solicitud de JSA ya no está disponible. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request is not valid. Return to WellBuilt Tickets and launch again.": "Esta solicitud de JSA no es válida. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request was already completed differently. Return to WellBuilt Tickets and launch again.": "Esta solicitud de JSA ya se completó de otra manera. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "This JSA request was already recorded. Return to WellBuilt Tickets.": "Esta solicitud de JSA ya fue registrada. Vuelva a WellBuilt Tickets.",
    "This JSA was updated. Check the locations below, then tap Acknowledge and add location again.": "Este JSA se actualizó. Revise las ubicaciones abajo y luego toque Reconocer y agregar ubicación de nuevo.",
    "This session cannot open a Tickets JSA request. Return to WellBuilt Tickets and launch again.": "Esta sesión no puede abrir una solicitud de JSA de Tickets. Vuelva a WellBuilt Tickets y abra el JSA de nuevo.",
    "Unable to reach WellBuilt. Check your connection and try again.": "No se pudo conectar con WellBuilt. Revise su conexión e inténtelo de nuevo.",
    "Unfinished JSA": "JSA sin terminar",
    "Unfinished JSAs": "JSA sin terminar",
    "Verifying your passcode...": "Verificando su código de acceso...",
    "Wells cancelled — didn't actually work": "Pozos cancelados — no se realizó el trabajo",
    "Wells could not load. You can enter a location manually.": "No se pudieron cargar los pozos. Puede ingresar una ubicación manualmente.",
    "WellBuilt sign-in is temporarily unavailable. Try again.": "El inicio de sesión de WellBuilt no está disponible temporalmente. Inténtelo de nuevo.",
    "Your JSA could not be saved on this device. Stay here and try again. Do not return to Tickets yet.": "Su JSA no se pudo guardar en este dispositivo. Permanezca aquí e inténtelo de nuevo. No vuelva a Tickets todavía.",
    "Your JSA is saved on this device, but WellBuilt could not record completion. Stay here and tap Retry. Do not return to Tickets yet.": "Su JSA está guardado en este dispositivo, pero WellBuilt no pudo registrar la finalización. Permanezca aquí y toque Reintentar. No vuelva a Tickets todavía.",
    "Your job details are ready. Continue to read your JSA.": "Los detalles del trabajo están listos. Continúe para leer su JSA.",
    "Your Name": "Su nombre",
    "Your name": "Su nombre",
    "Your passcode": "Su código de acceso",
    "{count} well:": "{count} pozo:",
    "{count} wells:": "{count} pozos:",
    "Add \"{name}\"": "Agregar \"{name}\"",
    "{app} is not installed on this device.": "{app} no está instalada en este dispositivo.",
    "Not Installed": "No instalada",
    "WellBuilt Suite is not installed on this device.": "WellBuilt Suite no está instalada en este dispositivo.",
    "Saving…": "Guardando…",
    "Skipped: {steps}": "Omitidos: {steps}",
    "Secure sign-in is not available for this account. Contact support.": "El inicio de sesión seguro no está disponible para esta cuenta. Comuníquese con soporte.",
    "Your JSA is saved on this device, but could not be queued for WellBuilt. Stay here and try again. Do not return to Tickets yet.": "Su JSA está guardado en este dispositivo, pero no se pudo poner en cola para WellBuilt. Permanezca aquí e inténtelo de nuevo. No vuelva a Tickets todavía.",
    "Your JSA is saved on this device, but it could not be securely archived. Do not tap Retry. Return to WellBuilt Tickets if you need a new request.": "Su JSA está guardado en este dispositivo, pero no se pudo archivar de forma segura. No toque Reintentar. Vuelva a WellBuilt Tickets si necesita una solicitud nueva.",
  },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    (async () => {
      try {
        const stored = await AsyncStorage.getItem(STORAGE_KEYS.language);
        if (stored === "es" || stored === "en") {
          setLangState(stored);
        }
      } catch {
        // ignore
      }
    })();
  }, []);

  const setLang = (next: Language) => {
    setLangState(next);
    AsyncStorage.setItem(STORAGE_KEYS.language, next).catch(() => {});
  };

  const toggleLang = () => {
    setLang(lang === "en" ? "es" : "en");
  };

  const t = (text: string, values?: Record<string, string | number>) => {
    const translated = translations[lang][text] || text;
    if (!values) return translated;
    return translated.replace(/\{(\w+)\}/g, (match, key) =>
      Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
    );
  };

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang,
      t,
    }),
    [lang]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return ctx;
};
